# This is the workflow to lint the source code
name: Publish

# Controls when the action will run.
on:
  # Allows you to call this workflow from other workflows
  workflow_call:
    secrets:
      CLOUDFLARE_ID:
        required: true
      CLOUDFLARE_API_TOKEN:
        required: true

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: 'ğŸš€ Publish'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    steps:
      - name: 'â˜ï¸ Checkout repository'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 'âš™ï¸ Use Node.js'
        uses: actions/setup-node@v3
        with:
          check-latest: true
          cache: 'npm'

      - name: 'â›“ï¸ Install dependencies'
        env:
          HUSKY: 0
        run: npm ci --no-optional --no-audit --prefer-offline --progress=false

      # In this repository, building is much faster than the upload/download of the artifact
      - name: 'ğŸ› ï¸ Build'
        run: npm run build --if-present

      # - name: 'ğŸ“ Download build output'
      #   uses: actions/download-artifact@v3
      #   continue-on-error: true # There won't be an artifact in workflow without build job
      #   with:
      #     name: build
      #     path: dist

      - name: 'ğŸš€ Publish to Cloudflare Pages'
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ID }}
          projectName: mh-photography
          directory: ./dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
