# This is the workflow to lint the source code
name: Publish

# Controls when the action will run.
on:
  # Allows you to call this workflow from other workflows
  workflow_call:
    secrets:
      CLOUDFLARE_ID:
        required: true
      CLOUDFLARE_API_TOKEN:
        required: true
      CLOUDFLARE_PROJECT_NAME:
        required: true
      INDEXNOW_KEY:
        required: false
    outputs:
      deployment-url:
        description: 'The URL of the deployed site'
        value: ${{ jobs.build.outputs.deployment-url }}

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: 'üöÄ Publish'
    runs-on: ubuntu-latest

    outputs:
      deployment-url: ${{ steps.cloudflare-deploy.outputs.deployment-url }}

    permissions:
      contents: read
      deployments: write

    steps:
      - name: '‚òÅÔ∏è Checkout repository'
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_branch || github.event.pull_request.base.ref }}

      - name: '‚öôÔ∏è Use Node.js'
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          check-latest: true
          cache: 'npm'

      - name: '‚õìÔ∏è Install dependencies'
        env:
          HUSKY: 0
        run: npm ci --no-audit --prefer-offline --progress=false

      - name: 'üìé Download build output'
        uses: actions/download-artifact@v6
        with:
          name: build
          path: dist
          run-id: ${{ github.event.workflow_run.id }}

      - name: Create IndexNow key file
        run: echo $INDEXNOW_KEY > dist/$INDEXNOW_KEY.txt
        env:
          INDEXNOW_KEY: ${{ secrets.INDEXNOW_KEY }}

      - name: 'üöÄ Publish to Cloudflare Pages'
        id: cloudflare-deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ID }}
          command: pages deploy ./dist --project-name=${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: 'üìù Save deployment URL'
        run: |
          echo "Deployed to: ${{ steps.cloudflare-deploy.outputs.deployment-url }}"
          echo "Alias URL: ${{ steps.cloudflare-deploy.outputs.pages-deployment-alias-url }}"

      - name: Notify IndexNow
        run: |
          if [ -z "${INDEXNOW_KEY}" ]; then
            echo "INDEXNOW_KEY is empty; skipping IndexNow notification.";
            exit 0;
          fi
          curl -H "Content-Type: application/json" \
            -d "{\"host\":\"th3s4mur41.me\",\"key\":\"$INDEXNOW_KEY\",\"urlList\":[\"https://th3s4mur41.me/sitemap-index.xml\"]}" \
            https://api.indexnow.org/indexnow
        env:
          INDEXNOW_KEY: ${{ secrets.INDEXNOW_KEY }}
